services:
  currency-conversion:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    environment:
      SPRING_R2DBC_URL: r2dbc:h2:file:///./testdb
      SPRING_R2DBC_USERNAME: sa
      SPRING_R2DBC_PASSWORD: password
      SPRING_H2_CONSOLE_ENABLED: "true"